// Tokens visuales para cada template del bracket.
// Solo UI — sin lógica, sin datos, sin funciones.
export const BRACKET_THEMES = {
  default: {
    id: 'default',
    nombre: 'Default',
    isDark: true,
    fontFamily: "'Inter', system-ui, sans-serif",
    wrapperBg: '#0d1117',
    wrapperBorder: 'rgba(255,255,255,0.08)',
    connStroke: 'rgba(255,255,255,0.22)',
    headerBg: 'linear-gradient(to bottom, #0a0f1a, #0d1117)',
    labelColor: 'rgba(255,255,255,0.45)',
    labelLetterSpacing: null,
    roundLabelStyle: 'default',
    cardLayout: 'default',
    cardBorderRadius: '12px',
    cardNameTransform: 'none',
    cardNameLetterSpacing: null,
    cardNameFontWeight: 400,
    cardRowPaddingY: '10px',
    cardSeedRadius: '3px',
    cardStyleOverride: null,
    cardBorderOverride: null,
    cardGlow: null,
    watermark: null,
    watermarkColor: null,
    sponsorsBg: '#f0f0ee',
    sponsorsTopBorder: null,
  },

  'world-tour-dark': {
    id: 'world-tour-dark',
    nombre: 'World Tour Dark',
    isDark: true,
    // Barlow Condensed: condensed, sporty, TV broadcast
    fontFamily: "'Barlow Condensed', sans-serif",
    wrapperBg: '#080c14',
    wrapperBorder: 'rgba(255,255,255,0.05)',
    connStroke: 'rgba(0, 220, 255, 0.70)',
    connGlow: true,
    headerBg: 'linear-gradient(135deg, #04080f 0%, #080c14 60%, #0a0e18 100%)',
    headerLayout: 'broadcast',
    labelColor: 'rgba(255,255,255,0.60)',
    labelLetterSpacing: '0.22em',
    roundLabelStyle: 'boxed',
    cardLayout: 'flat',
    cardBorderRadius: '2px',
    cardNameTransform: 'uppercase',
    cardNameLetterSpacing: '0.04em',
    cardNameFontWeight: 600,
    cardRowPaddingY: '7px',
    cardSeedRadius: '2px',
    cardStyleOverride: 'oscura',
    cardBorderOverride: 'rgba(255,255,255,0.08)',
    cardGlow: null,
    watermark: 'MAIN DRAW',
    watermarkColor: 'rgba(255,255,255,0.025)',
    sponsorsBg: '#0d0d14',
    sponsorsTopBorder: null,
  },

  'electric-blue': {
    id: 'electric-blue',
    nombre: 'Electric Blue',
    isDark: true,
    // Exo 2: tech/futuristic, sharp
    fontFamily: "'Exo 2', sans-serif",
    wrapperBg: '#030b18',
    wrapperBorder: 'rgba(56,182,255,0.18)',
    connStroke: '#38b6ff',
    connGlow: true,
    headerBg: 'linear-gradient(135deg, #040e20 0%, #071428 60%, #050f1e 100%)',
    headerLayout: 'electric',
    labelColor: '#38b6ff',
    labelLetterSpacing: '0.12em',
    roundLabelStyle: 'boxed',
    cardLayout: 'stat',
    cardBorderRadius: '8px',
    cardNameTransform: 'uppercase',
    cardNameLetterSpacing: '0.03em',
    cardNameFontWeight: 600,
    cardRowPaddingY: '9px',
    cardSeedRadius: '50%',
    cardStyleOverride: 'transparente',
    cardBorderOverride: 'rgba(56,182,255,0.30)',
    cardGlow: '0 0 18px rgba(56,182,255,0.18), 0 0 1px rgba(56,182,255,0.40)',
    watermark: 'DRAW',
    watermarkColor: 'rgba(56,182,255,0.03)',
    sponsorsBg: '#040c1a',
    sponsorsTopBorder: 'rgba(56,182,255,0.50)',
  },

  'minimal-pro': {
    id: 'minimal-pro',
    nombre: 'Minimal Pro',
    isDark: false,
    // DM Sans: clean, editorial, draw sheet de tenis (Wimbledon/ATP)
    fontFamily: "'DM Sans', sans-serif",
    wrapperBg: '#fbfbf9',
    wrapperBorder: '#ececea',
    connStroke: 'rgba(15,23,42,0.14)',
    connGlow: false,
    headerBg: '#ffffff',
    headerLayout: 'minimal',
    labelColor: '#94a3b8',
    labelLetterSpacing: '0.28em',
    roundLabelStyle: 'minimal',
    cardLayout: 'sheet',
    cardBorderRadius: '0px',
    cardNameTransform: 'none',
    cardNameLetterSpacing: '0.01em',
    cardNameFontWeight: 500,
    cardRowPaddingY: '11px',
    cardSeedRadius: '50%',
    cardStyleOverride: 'clara',
    cardBorderOverride: null,
    cardGlow: null,
    watermark: null,
    watermarkColor: null,
    sponsorsBg: '#ffffff',
    sponsorsTopBorder: '#e5e7eb',
  },

  'neon-arena': {
    id: 'neon-arena',
    nombre: 'Neon Arena',
    isDark: true,
    // Chakra Petch: cyberpunk, aggressive, angular — HUD esports
    fontFamily: "'Chakra Petch', sans-serif",
    wrapperBg: '#040504',
    wrapperBorder: 'rgba(0,255,180,0.18)',
    connStroke: '#00ffb4',
    connGlow: true,
    headerBg: 'linear-gradient(135deg, #060a07 0%, #040504 60%, #06090a 100%)',
    headerLayout: 'arena',
    labelColor: 'rgba(0,255,180,0.90)',
    labelLetterSpacing: '0.18em',
    roundLabelStyle: 'arena',
    cardLayout: 'arena',
    cardBorderRadius: '0px',
    cardNameTransform: 'uppercase',
    cardNameLetterSpacing: '0.01em',
    cardNameFontWeight: 600,
    cardRowPaddingY: '8px',
    cardSeedRadius: '0px',
    cardStyleOverride: 'oscura',
    cardBorderOverride: 'rgba(0,255,180,0.30)',
    cardGlow: '0 0 16px rgba(0,255,180,0.10)',
    watermark: null,
    watermarkColor: null,
    sponsorsBg: '#050505',
    sponsorsTopBorder: 'rgba(0,255,180,0.60)',
  },

  'championship-gold': {
    id: 'championship-gold',
    nombre: 'Championship Gold',
    isDark: true,
    // Cinzel: serif clásico, ceremonial — placa de honor grabada
    fontFamily: "'Cinzel', serif",
    wrapperBg: '#080601',
    wrapperBorder: 'rgba(212,175,55,0.22)',
    connStroke: 'rgba(212,175,55,0.55)',
    connGlow: false,
    headerBg: 'linear-gradient(to bottom, #0a0702 0%, #0d0a02 70%, #080601 100%)',
    headerLayout: 'gold',
    labelColor: 'rgba(212,175,55,0.62)',
    labelLetterSpacing: '0.22em',
    roundLabelStyle: 'gold',
    cardLayout: 'gold',
    cardBorderRadius: '3px',
    cardNameTransform: 'uppercase',
    cardNameLetterSpacing: '0.01em',
    cardNameFontWeight: 400,
    cardRowPaddingY: '9px',
    cardSeedRadius: '2px',
    cardStyleOverride: 'oscura',
    cardBorderOverride: 'rgba(212,175,55,0.30)',
    cardGlow: '0 1px 14px rgba(0,0,0,0.45)',
    watermark: null,
    watermarkColor: null,
    sponsorsBg: '#080601',
    sponsorsTopBorder: '#d4af37',
  },
}

export const BRACKET_TEMPLATE_LIST = Object.values(BRACKET_THEMES)
